# Build environment
###################
FROM node:13.12.0-alpine AS builder

# Create and set working directory
RUN mkdir /src
WORKDIR /src

# Add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /src/node_modules/.bin:$PATH

# Environment variable
ARG REACT_APP_API_ROOT=$REACT_APP_API_ROOT
ARG REACT_APP_DATA_API_ROOT=$REACT_APP_DATA_API_ROOT

# Install and cache app dependencies
COPY package*.json /src/
RUN npm install

# Copy in source files
COPY . /src

# Build app
RUN npm run build


# Production environment
########################
FROM nginx:1.19.1

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /src/build /usr/share/nginx/html/

RUN touch /var/run/nginx.pid && \
    chown -R www-data:www-data /var/run/nginx.pid && \
    chown -R www-data:www-data /var/cache/nginx && \
    chown -R www-data:www-data /usr/share/nginx/html

USER www-data

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
